### PR TITLE
Implement API for username availability

### PR DESCRIPTION
**Pull request by lukebarnard1**
Requires synapse with https://github.com/matrix-org/synapse/pull/2183 and https://github.com/matrix-org/synapse/pull/2209 

**Update**: this needs to be changed to reflect https://github.com/matrix-org/synapse/pull/2213

### CODE REVIEW

**Comment by krombel** [comment]
To be correct it requires matrix-org/synapse#2209

**Comment by lukebarnard1** [comment]
thanks, @krombel

**Comment by richvdh** [comment]
looks ok, but why is this a POST rather than a GET?

**Comment by lukebarnard1** [comment]
@richvdh I made the mistake of thinking a `GET` can include a body, which inherently it cannot. Hence https://github.com/matrix-org/synapse/pull/2209

**Comment by lukebarnard1** [comment]
>yes, but why put the user id in the body rather than a query param?

Good question. When I originally proposed this, the response was largely "small things like this don't need a proposal". Things like this would probably have been looked at if a proposal was made.

**Comment by lukebarnard1** [comment]
I shall modify this PR to reflect the changes to the synapse API - it shall be a `GET` with a query parameter instead.

**Comment by krombel** [comment]
What is in case we want to trigger this function where this endpoint is not implemented?
Shouldn't the function raise such an error or do we assume the developer just triggers this function when he knows that this is available (then how should he determine)

**Comment by lukebarnard1** [comment]
@krombel if the endpoint is not available on the server, a `MatrixError` will be raised with the `errcode` set to `M_UNRECOGNIZED`.

**Comment by krombel** [comment]
OK. Good to know. Thanks

**Pull request merged**
