### PR TITLE
Element R: Implement `requestOwnUserVerification`

### PR DESCRIPTION
**Pull request by richvdh**
Based on #3497

Part of https://github.com/vector-im/element-web/issues/25319.

Notes: Support for interactive device verification in Element-R.

---
Here's what your changelog entry will look like:

## ✨ Features
 * Support for interactive device verification in Element-R. ([\#3503](https://github.com/matrix-org/matrix-js-sdk/pull/3503)).

### CODE REVIEW

**Review by t3chguy — DISMISSED** [review]
https://github.com/matrix-org/matrix-js-sdk/pull/3503/commits/6f7bcde904a416675ac83e088545046b00b8c5aa looks sane. In future for stacked PRs which are not in draft could you please set the base branch correctly so that the Files changed tab doesn't try to make me review multiple PRs in one fell swoop?

**Comment by richvdh** [comment]
@t3chguy: now rebased, PTAL

**Review by t3chguy — APPROVED** [review]
:shipit:

**Comment by richvdh** [comment]
I merged this into the wrong branch, and had to revert it.

Another go, at #3508.

**Pull request merged**
