### PR TITLE
Rework how disambiguation is handled

### PR DESCRIPTION
**Pull request by SimonBrandner**
This adds a `disambiguate` property to the `RoomMember`. This is useful when a client wants to handle more things on its own. For example, a client may wish to format the `displayName` differently than the `userId` and therefore has to retrieve the `displayName` and `userName` separately - it can't rely on `js-sdk`'s calculation of display names.

### CODE REVIEW

**Comment by turt2live** [comment]
@ShadowJonathan this contains commits from you - can we get sign off on it please?
@SimonBrandner can we also get sign off on the couple commits that aren't signed off please?

**Review by turt2live — APPROVED** [review]
otherwise lgtm

**Comment by SimonBrandner** [comment]
```
Signed-off-by: Šimon Brandner <simon.bra.ag@gmail.com>
```

**Comment by ShadowJonathan** [comment]
`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

**Pull request merged**
