### PR TITLE
Fix paginateEventTimeline resolve to boolean

### PR DESCRIPTION
**Pull request by ajbura**
Earlier paginateEventTimeline used to resolve to  chunk instead of resolving to boolean. Now it resolve to boolean as specified in doc.

Signed-off-by: Ajay Bura <ajbura@gmail.com>

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Fix paginateEventTimeline resolve to boolean ([\#2054](https://github.com/matrix-org/matrix-js-sdk/pull/2054)). Contributed by @ajbura.

### CODE REVIEW

**Comment by t3chguy** [comment]
Can you type https://github.com/matrix-org/matrix-js-sdk/pull/2054/files#diff-25d66d74617fe2e23d7946bd6e3ba95640ab1b9bc8947445d604fc271c7c1f12R5068-R5070 these whilst you're here, these not being implicit any would have caught this bug.

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/2055 types L5068-L5069

**Review by t3chguy — APPROVED** [review]
LGTM other than the ask to fix the type to prevent this issue in the future

**Comment by ajbura** [comment]
Hi, I have tried it but isn't confident that I am doing it correctly. (Complete noob with typescript here :))

**Pull request merged**
