### PR TITLE
Fix regressed glare

### PR DESCRIPTION
**Pull request by SimonBrandner**
This should fix [#17250](https://github.com/vector-im/element-web/issues/17250).

### CODE REVIEW

**Review by dbkr — APPROVED** [review]

**Comment by dbkr** [comment]
Oh, good spot, thanks!

**Comment by jryans** [comment]
I'll go ahead and backport this to the release as well.

**Comment by ara4n** [comment]
@SimonBrandner thanks! :)

**Comment by SimonBrandner** [comment]
No problem :)

**Pull request merged**
