### PR TITLE
make leaveRoomSession async

### PR DESCRIPTION
**Pull request by toger5**
This does not resolve the promise until the event is actually send. No network connection would make awaiting on this blocking.

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by dbkr — COMMENTED** [review]
The description of this PR is great and documents what the contract of this function is. Could it go in the docs for the function.? :)

Also is this definitely what we want? If you lose your net connection will you just be unable to leave?

**Comment by toger5** [comment]
I am not sure. To some extend this is how it is. You cannot leave (remove the memberships) if there is no network connection.
I can imagine that its frontend logic to also provide a timeout (`await Promise.all([endCall, timeout(20sek)])`) but the end call function only returns if it finally and actually managed to end the call.

**Comment by dbkr** [comment]
Yeah, this probably does make sense for the js-sdk part. It would be nice to have the function docced though.

**Comment by toger5** [comment]
are u imagining: 
```
/*
* Will try to leave a rtc session and do periodic retries. If a timeout is provided this will resolve after the timeout even if the 
* leave was not sucessful. The success is indicated with the bool.
*/
leaveRoomSession(timeout: Number|undefined = undefined): Future<bool>
```

**Comment by dbkr** [comment]
Yep, and ideally be explicit about when it resolved with no timeout provided, eg. "resolves once the updated member event has been sent, or if timeout is a positive number, after this time or whichever is sooner."

**Review by dbkr — APPROVED** [review]

**Pull request merged**
