### PR TITLE
Wire up verification cancel & mismatch for rust crypto

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/element-hq/element-web/issues/27394

### CODE REVIEW

**Comment by richvdh** [comment]
Thank you for picking this up, though it makes me very uneasy that we don't have a test (preferably an end-to-end one, using playwright) for this. The lack of tests is why we have all these rough edges in the first place :(.

**Comment by t3chguy** [comment]
Fair, I did test it myself, can I sign a deed poll to rename myself to `Mr. Playwright` or does that not count?

**Review by richvdh — APPROVED** [review]
The change looks plausible

**Comment by t3chguy** [comment]
I'll add a boring old automated Playwright test on https://github.com/matrix-org/matrix-react-sdk/pull/12526

**Comment by richvdh** [comment]
FWIW, there's also a not-bad suite of Jest tests for verification at the js-sdk level in `spec/intec/crypto/verification.spec.ts`, which would also be nice to extend. But given a choice between that and a playwright test, I'd probably prefer the playwright one.

**Comment by t3chguy** [comment]
Playwright test wired, had to disable it for legacy crypto as that doesn't show the expected mismatch modal and only shows the cancelled state as it does not set the `cancellationCode` as expected. Given its legacy and hopefully being ditched soon I don't think its worth digging into further.

**Review by andybalaam — APPROVED** [review]
Nice, thank you t3chguy!

**Pull request merged**
