### PR TITLE
Revert "Update JS-DevTools/npm-publish action to v2 (#3336)"

### PR DESCRIPTION
**Pull request by andybalaam**
Attempting to fix failure to publish to NPM due to an "invalid token" error https://github.com/matrix-org/matrix-js-sdk/actions/runs/4926808655/jobs/8819822367 .

This reverts commit ca9263fa647e4cfc581a137c389ea646bcf71ce6.

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by t3chguy** [comment]
Indeed, due to the major update of npm-publish, the `.npmrc` file no longer contains the token after the run of the action

> The user's ~/.npmrc file is no longer modified. Instead, a temporary .npmrc file is used. (https://github.com/JS-DevTools/npm-publish/issues/15)

So the subsequent npm commands fail.

Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/3336

**Review by t3chguy — APPROVED** [review]

**Comment by andybalaam** [comment]
> So the subsequent npm commands fail.

Which subsequent npm commands? I only see one in this workflow.

**Comment by t3chguy** [comment]
@andybalaam 

https://github.com/matrix-org/matrix-js-sdk/blob/develop/.github/workflows/release-npm.yml#L25-L31 runs `npm publish`, with v1 it first sets up the `.npmrc` file - with v2 it sets up a temporary one that gets thrown away

https://github.com/matrix-org/matrix-js-sdk/blob/develop/.github/workflows/release-npm.yml#L37 is the subsequent (not publish) npm command.

**Comment by andybalaam** [comment]
@t3chguy ah, thank you! I was not making the leap from release.yml to release-npm.yml

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-js-sdk/blob/develop/.github/workflows/release.yml#L38-L42 https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by andybalaam** [comment]
Feels like we should be able to specify multiple tags to npm-publish. I'll look at that if I have time.

**Comment by t3chguy** [comment]
That would be a nice modification, but the underlying `npm publish` command doesn't support it

**Pull request merged**
