### PR TITLE
Remove Bluebird: phase 3

### PR DESCRIPTION
**Pull request by t3chguy**

### CODE REVIEW

**Comment by turt2live** [comment]
I feel like something went wrong with this PR.

**Comment by t3chguy** [comment]
indeed it did. REBASE TIME :D

**Comment by t3chguy** [comment]
oh wait, it was based against the previous pr, obviously that was going to do that :D

**Comment by turt2live** [comment]
@t3chguy it's confusing reviewing my own PR in your PR ... what's the plan for these branches?

**Comment by t3chguy** [comment]
@turt2live fixed that, it is awaiting review so that I can merge this and https://github.com/matrix-org/matrix-js-sdk/pull/1100 at the same time

**Pull request merged**
