### PR TITLE
Add local volume control

### PR DESCRIPTION
**Pull request by SimonBrandner**
For https://github.com/vector-im/element-call/pull/468

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by robintown** [comment]
I'm trying to understand how this works - is `localVolume` or the event hooked up to anything?

**Comment by SimonBrandner** [comment]
> I'm trying to understand how this works - is `localVolume` or the event hooked up to anything?

Yes, it is in https://github.com/vector-im/element-call/pull/468

**Comment by robintown** [comment]
Oh, I see, volume has to be set on the media element in the front-end

**Review by robintown — APPROVED** [review]

**Comment by SimonBrandner** [comment]
(going to block this until the element-call side is ready)

**Comment by SimonBrandner** [comment]
Unblocking and merging as the element-call side got product approval

**Pull request merged**
