### PR TITLE
Modernize window.crypto access constants

### PR DESCRIPTION
**Pull request by turt2live**
For https://github.com/element-hq/element-web/pull/27326

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [x] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [x] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Comment by turt2live** [comment]
I believe the Element Web build error is failed (or lack of) branch matching to the react-sdk.

**Comment by turt2live** [comment]
Sorry for the spam here. As is hopefully obvious from the commit history, I tried to use `@types/serviceworker` and that exploded in my face for the 8th time this week.

My vote is to give up for now and put a help wanted label on it.

**Review by richvdh — CHANGES_REQUESTED** [review]
I don't really know why we're indirecting via `window` in the first place. [`crypto`](https://developer.mozilla.org/en-US/docs/Web/API/crypto_property) is defined as a global property - ie, it should be available via `globalThis` in all environments.

I suspect it's because this code predates the existence of `globalThis`, so used to say `crypto = window.crypto`, which then got (incorrectly, imho) turned into `crypto = globalThis.window.crypto`.

Likewise TextEncoder.

**Comment by richvdh** [comment]
> My vote is to give up for now and put a help wanted label on it.

I don't really understand. If you're not going to keep working on the PR, could you close it please?

**Comment by turt2live** [comment]
I'm not sure I understand the action requested here. Should the crypto indirection be removed?

As for closing the PR: I'm saying we give up on trying to get types to work, but the PR is required to work. I cannot commit to debugging the entire type system much further, so a help wanted issue feels like the correct approach.

**Comment by richvdh** [comment]
> I'm not sure I understand the action requested here. Should the crypto indirection be removed?

I'm suggesting that, rather than doing anything special for service workers, you change lines 19-21 to be:

```
export let crypto = globalThis.crypto;
export let subtleCrypto = crypto?.subtle ?? crypto?.webkitSubtle;  // or just `crypto?.subtle`
export let TextEncoder = globalThis.TextEncoder;
```

... and be done.

> As for closing the PR: I'm saying we give up on trying to get types to work, but the PR is required to work. I cannot commit to debugging the entire type system much further, so a help wanted issue feels like the correct approach.

oh right. Well, that was far from obvious from your comment :)

**Review by richvdh — APPROVED** [review]
LGTM, though needs an update to the PR title.

**Pull request merged**
