### PR TITLE
Refactor all of the js-sdk to ES6

### PR DESCRIPTION
**Pull request by Jack-Works**
Signed-off-by: Jack Works <jackworks@protonmail.com>

Does not include any style related change.

### CODE REVIEW

**Comment by Jack-Works** [comment]
> please open 1 PR for all the classes for easier handling on our side. Some style changes are expected, like indenting the functions to match the class declaration.
> 
> Would it be helpful to talk this over in #riot-dev:matrix.org?

Got it, I'll append future commit to this branch

**Comment by Jack-Works** [comment]
@turt2live Hi my work is done!

**Comment by turt2live** [comment]
Thanks @Jack-Works - I'll try to review this later this week, though at a glance it is looking much better. We're still cautious about landing this before some large demos at FOSDEM, but should be landed by next week sometime.

**Comment by turt2live** [comment]
Right, it's after FOSDEM now - I'll try and take a look on Monday. Thanks again for doing all this work!

**Comment by Jack-Works** [comment]
hello, any progress?

**Comment by turt2live** [comment]
sorry, I ended up getting busy and haven't had a chance to look. Plan is still to look at it Monday, though probably in the evening.

**Comment by Jack-Works** [comment]
hi? it's conflicting more and more now

**Comment by turt2live** [comment]
sorry for the delay on this - large/structural changes are extremely difficult for us to get through our queue. The files that do conflict aren't going to be merged here until the project has less commit traffic going through it (we're also at a point of critical release so don't want to impede development of the features touching those files), however the other files will be cherry picked into the project. 

At a glance, things look fine but I do need to do some side-by-side comparison first. I'm aiming to do this before Monday, but do apologize if it doesn't make it.

**Comment by turt2live** [comment]
Right, I've pulled in all the files that merged cleanly here: https://github.com/matrix-org/matrix-js-sdk/pull/1229

There's some additional work to be done to make the CI happy (tests, linting, etc), but I can take that on. I'm going to leave this PR open to flag that there's still 9 files which need conversion.

Thanks again for the contribution!

**Comment by Jack-Works** [comment]
> Right, I've pulled in all the files that merged cleanly here: #1229
> 
> There's some additional work to be done to make the CI happy (tests, linting, etc), but I can take that on. I'm going to leave this PR open to flag that there's still 9 files which need conversion.
> 
> Thanks again for the contribution!

Cool! Happy to see that. Free to @ me to rebase this PR to resolve the rest of the files!

**Comment by Jack-Works** [comment]
👀I have checkout the project again found there are no (or few) commits get picked. 

image

**Comment by jryans** [comment]
https://github.com/matrix-org/matrix-js-sdk/pull/1229 is a draft PR that has not yet been merged.

**Comment by turt2live** [comment]
I think in practice we've ended up converting most of it by hand to TS. If there's still bits that are remaining then feel free to open PRs for those pieces, but I don't think we can reasonably keep this PR going.

Thank you for putting in the effort, and sorry it took so long to review :(

**Pull request closed without merging**
