### PR TITLE
Send a STOPPED sync updated after call to stopClient

### PR DESCRIPTION
**Pull request by fred-wang**

### CODE REVIEW

**Comment by Kegsay** [comment]
@dbkr - Since you implemented the `STOPPED` state, can you please check this?

**Comment by fred-wang** [comment]
I believe this happens when one call MatrixClient::stopClient while the this._currentSyncRequest request in SyncApi::_sync is still executed. Then SyncApi::stop() is called, setting this._running to false and aborting this._currentSyncRequest. This then leads to the place where the code is added in this commit.

**Comment by dbkr** [comment]
Yep, this should definitely have been there: thanks.

Sorry, but can you do the DCO signoff please? (https://github.com/matrix-org/matrix-js-sdk/blob/master/CONTRIBUTING.rst)

**Comment by fred-wang** [comment]
Signed-off-by: Frédéric Wang <fred.wang@free.fr>

**Comment by dbkr** [comment]
Thanks!

**Pull request merged**
