### PR TITLE
Remove deprecated authedRequestWithPrefix and requestWithPrefix

### PR DESCRIPTION
**Pull request by t3chguy**
replacing as documented with authedRequest

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/991

Signed-off-by: Michael Telatynski <7t3chguy@gmail.com>

### CODE REVIEW

**Comment by turt2live** [comment]
We should treat it as a major change, although not breaking I think. They've been deprecated for years so it's possible albeit unlikely that someone is using it.

**Comment by jryans** [comment]
> We should treat it as a major change, although not breaking I think.

Okay, so does that mean only minor version bump, like with a new feature, etc.?

**Comment by turt2live** [comment]
It means that I think we should actually measure impact and make a decision off the data. Some searches in GitHub are likely to reveal places where people might be impacted.

I do suspect we can get away with a minor bump though.

**Comment by turt2live** [comment]
@jryans I'm starting to think that we should just push it through a minor release (2.x.0) rather than as a breaking change. The only thing I can find still using these is the IRC bridge, which @Half-Shot can fix if it's still a thing (looks like it's a test for the bridge).

What are your thoughts? (also can we merge it so it gets out of the review column?)

**Comment by jryans** [comment]
Thanks for checking the ecosystem! Minor release sounds fine to me as well then.

Yes, let's merge this. (I should have been clearer upfront that we did not need to resolve the version decision before merging...)

**Pull request merged**
