### PR TITLE
Use ts-xor package for XOR type

### PR DESCRIPTION
**Pull request by AndrewFerr**
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [x] Linter and other CI checks pass.
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Comment by AndrewFerr** [comment]
Amended the commit to include the rationale.

**Comment by t3chguy** [comment]
I'm not sure I personally agree with this. Using packages for a handful of lines of source is an antipattern quite common in Node/Javascript ecosystem and just increased risk of supply chain attacks.

**Comment by AndrewFerr** [comment]
A tangible benefit of the ts-xor package is the ability to [XOR more than two types](https://github.com/maninak/ts-xor/tree/master#xoring-more-than-two-types).

But you make a good point about supply chain attacks.

**Comment by MidhunSureshR** [comment]
Closing since the package isn't really needed for now, please reopen if you disagree.

**Pull request closed without merging**
