### PR TITLE
Stabilise token authenticated registration support

### PR DESCRIPTION
**Pull request by govynnus**
Token authenticated registration was added to the Matrix specification in v1.2:
https://spec.matrix.org/v1.2/client-server-api/#token-authenticated-registration

Signed-off-by: Callum Brown <callum@calcuode.com>

---
Here's what your changelog entry will look like:

## ✨ Features
 * Stabilise token authenticated registration support ([\#2181](https://github.com/matrix-org/matrix-js-sdk/pull/2181)). Contributed by @govynnus.

### CODE REVIEW

**Comment by govynnus** [comment]
I believe Synapse is the only server implementing this, and there is a release candidate (1.53.0rc1) which uses the stable version:
https://github.com/matrix-org/synapse/blob/develop/CHANGES.md#synapse-1530rc1-2022-02-15

Ruma has also made the change, but I don't think it's released yet:
https://github.com/ruma/ruma/commit/f63168538970c76bdd1639c27606442a80a567a9

**Comment by govynnus** [comment]
Ok.
How would supporting both types work?

Also, Synapse 1.53.0.rc1 does not maintain backwards compatibility, so without support for the stable version the functionality will break for matrix-js-sdk users of updated servers.

**Comment by turt2live** [comment]
The server doesn't need to maintain backwards compatibility in this case, but we as a client won't know what version of the server we're talking to so need to handle the case where legacy servers offer the unstable flows. 

We've implicitly made the decision to support the unstable identifiers by implementing it, so need to maintain that until servers have upgraded enough where it's reasonable for us to remove the backwards compatibility ourselves. 

Usually we avoid this problem entirely by not using enums (because they can't support stable and unstable at the same time), but given we don't really have a choice we end up with `UnstableRegistrationToken` and `RegistrationToken`, then annotate and document the differences between the flows.

**Comment by govynnus** [comment]
How does that look?

**Comment by govynnus** [comment]
@turt2live Hi, any chance you could have a look at this this week?

**Review by turt2live — APPROVED** [review]
Thanks!

**Pull request merged**
