### PR TITLE
Add config option for e2e group call signalling

### PR DESCRIPTION
**Pull request by dbkr**
---
Here's what your changelog entry will look like:

## ✨ Features
 * Add config option for e2e group call signalling ([\#2492](https://github.com/matrix-org/matrix-js-sdk/pull/2492)).

### CODE REVIEW

**Review by SimonBrandner — COMMENTED** [review]
Would it make more sense for this to be a per-call setting?

**Comment by dbkr** [comment]
So the reason I didn't do it per-call or anywhere in the signalling is because that then allows the server to do a downgrade attack. This feels a bit harder to force clients to downgrade to not using encryption.

**Comment by SimonBrandner** [comment]
> So the reason I didn't do it per-call or anywhere in the signalling is because that then allows the server to do a downgrade attack. This feels a bit harder to force clients to downgrade to not using encryption.

Sorry, I am not very familiar with this, so I am not seeing how exactly this should happen; though my main concern now is https://github.com/vector-im/element-call/pull/438#discussion_r913241512

**Review by SimonBrandner — APPROVED** [review]
LGTM and thank you for answering all my questions!

**Pull request merged**
