### PR TITLE
fix accumulated sync summaries - andy review

### PR DESCRIPTION
**Pull request by ara4n**
incorporate andy's review

---
This PR currently has none of the required changelog labels.

Add one of: `T-Deprecation`, `T-Enhancement`, `T-Defect`, `T-Task` to indicate what type of change this is plus `X-Breaking-Change` if it's a breaking change.

### CODE REVIEW

**Comment by ara4n** [comment]
going to force-merge given this doesn't need review given it's just incorporating existing review

**Comment by richvdh** [comment]
@ara4n ... and if you *must* force-merge, please at least wait for CI to complete.

> going to force-merge given this doesn't need review given it's just incorporating existing review

where did this review take place?

**Comment by ara4n** [comment]
> @ara4n please avoid force merging in future

ack

> where did this review take place?

https://github.com/matrix-org/matrix-js-sdk/pull/3366 - i'm not making it up......

**Review by andybalaam — COMMENTED** [review]
Approved.

**Comment by richvdh** [comment]
> #3366 - i'm not making it up......

I'm sure you're not, but it's helpful to keep a record to help future investigations.

Thanks for clarifying.

**Pull request merged**
