### PR TITLE
Add simple browserify browser-matrix.js tests

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1216

Yay more imports fun. Broke somewhere around typescript/webpack changes.

### CODE REVIEW

**Comment by t3chguy** [comment]
image
https://buildkite.com/matrix-dot-org/matrix-js-sdk/builds/1296#368d4c2c-41e8-423c-b60e-31888191c129

**Comment by turt2live** [comment]
So I spent the better part of the afternoon trying to figure out why Jest is angry about this and the conclusion is I have no idea. We can do something jank like the following (which does work in all 3 environments), but it's jank and not something I'd even approve of:

```js
import unhomoglyph1 from "unhomoglyph";
import * as unhomoglyph2 from "unhomoglyph";
// ... snip ...
return (unhomoglyph1 || unhomoglyph2)(str);
```

Looks like something deep within Jest doesn't get along with the TypeScript ES6 import for a CommonJS module, and even trying to ship the TypeScript declarations (https://github.com/nodeca/unhomoglyph/pull/6) for the package doesn't work. 

This probably needs a bunch more engineering time - I can try to take a look, but given it's taken this long and I'm still at square 1 it'll be near the bottom of my list. If someone else has time/ideas/a clearer picture feel free to take this on.

**Comment by menturion** [comment]
I replaced `import unhomoglyph from 'unhomoglyph';`  by `const unhomoglyph = require('unhomoglyph');` in `utils.ts` and built it. The browser version seems to work fine w/o any issue.

**Comment by turt2live** [comment]
> There are no new changes to show.

@t3chguy you've managed to create a PR which does nothing :p

**Comment by t3chguy** [comment]
That was my point, it seems to be fixed without this PR needed. Am doing a test in all 3 envs as per RWI now.

**Comment by t3chguy** [comment]
Its running out of heap, probably from having to load and parse the browserified bundle.

**Comment by t3chguy** [comment]
Not the best test coverage but is a regression test for the unhomoglyph thing

```
------------------------------------|----------|----------|----------|----------|-------------------|
File                                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------|----------|----------|----------|----------|-------------------|
All files                           |    34.11 |    22.39 |    32.88 |    35.55 |                   |
 dist                               |    19.11 |     6.85 |    18.23 |     20.2 |                   |
  browser-matrix.js                 |    19.11 |     6.85 |    18.23 |     20.2 |... 12,67113,67122 |
```

**Pull request merged**
