### PR TITLE
Don't hang up calls that haven't started yet

### PR DESCRIPTION
**Pull request by dbkr**
## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Don't hang up calls that haven't started yet ([\#2898](https://github.com/matrix-org/matrix-js-sdk/pull/2898)).

### CODE REVIEW

**Review by robintown — COMMENTED** [review]
I'd be interested to know how it's possible for `disposeCall` to get called before the call starts, just to make sure that this is the right place to fix this

**Comment by dbkr** [comment]
Sondarcloud seems to want me to refactor `onCallFeedsChanged` which hasn't changed in this PR...

**Comment by dbkr** [comment]
I strongly suspect it's if the call gets replaced before it's had a chance to send the invite

**Comment by t3chguy** [comment]
> Sondarcloud seems to want me to refactor onCallFeedsChanged which hasn't changed in this PR...


Likely your base branch is out of date and thus re-introduces the issue

**Comment by robintown** [comment]
@dbkr Then would https://github.com/matrix-org/matrix-js-sdk/blob/c389de98f36787f862173973b22079248eb351ae/src/webrtc/call.ts#L1082 perhaps be a more appropriate place to put this? Otherwise the replaced call would never clean up its holds on the streams, I think

**Comment by dbkr** [comment]
Very good point - in fact that check should have included both the states in which we wouldn't have sent an invite anyway.

**Review by robintown — APPROVED** [review]

**Pull request merged**
