### PR TITLE
Support optional MSC3860 redirects

### PR DESCRIPTION
**Pull request by turt2live**
See `allow_redirect` across the media endpoints: https://spec.matrix.org/v1.9/client-server-api/#client-behaviour-7

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## ✨ Features
 * Support optional MSC3860 redirects ([\#4007](https://github.com/matrix-org/matrix-js-sdk/pull/4007)).

### CODE REVIEW

**Review by t3chguy — APPROVED** [review]

**Comment by uhoreg** [comment]
@turt2live I don't know if you noticed, but this PR got removed from the review queue due to [failing downstream tests](https://github.com/matrix-org/matrix-js-sdk/actions/runs/7532107347/job/20503050302).  Looks like you need to make a PR for react-sdk to handle the new URLs that this PR creates.

**Comment by turt2live** [comment]
There is a react-sdk PR: https://github.com/matrix-org/matrix-react-sdk/pull/12142

**Comment by t3chguy** [comment]
After discussing with Travis, to avoid a backwards incompatible change (for tests at least) we've gone with only sending the param if a boolean is passed for the new param

**Review by turt2live — COMMENTED** [review]
I can't approve my own PR, but explicit behaviour lgtm, thanks :)

**Pull request merged**
