### PR TITLE
fix(login): saves access_token and user_id after login for all login types

### LINKED ISSUE #876: login using jwt gives access token error
Related to #130, logging in with JWT does not automatically update the client with the returned access token and user_id. A new client has to be created instead.

This doesn't work:
```js
const matrixClient = createClient({ baseUrl: BASE_URL });
await matrixClient.login('m.login.jwt', { token: jwtToken });
await matrixClient.startClient();
```

Workaround:
```js
const tempClient = createClient({ baseUrl: BASE_URL });
const { access_token, user_id } = await tempClient.login('m.login.jwt', { token: jwtToken });
const matrixClient = createClient({
  baseUrl: BASE_URL,
  accessToken: access_token,
  userId: user_id,
});
await matrixClient.startClient();
```

Fix likely similar to PR https://github.com/matrix-org/matrix-js-sdk/pull/778

### PR DESCRIPTION
**Pull request by stalniy**
Signed-off-by: Sergii Stotskyi <sergiy.stotskiy@gmail.com>

Fixes #876

### CODE REVIEW

**Comment by jryans** [comment]
@turt2live Should this be considered a breaking change (since it updates the existing client in place)? (A similar change for password login only https://github.com/matrix-org/matrix-js-sdk/pull/778 was treated that way.)

**Comment by turt2live** [comment]
Error, yes, probably. Did I make a ness of things?

**Comment by jryans** [comment]
Haha, well, I guess we could include it 2.0.0 along with https://github.com/matrix-org/matrix-js-sdk/pull/931?

**Comment by turt2live** [comment]
Probably. Would make for an easier release.

**Pull request merged**
