### PR TITLE
mention deno support in the README

### PR DESCRIPTION
**Pull request by sigmaSd**
Type: enhancement

It seems to work fine, and I have a demo bot with it https://github.com/sigmaSd/deno-matrix-bot

---
Here's what your changelog entry will look like:

## ✨ Features
 * mention deno support in the README ([\#3417](https://github.com/matrix-org/matrix-js-sdk/pull/3417)). Contributed by @sigmaSd.

### CODE REVIEW

**Comment by sigmaSd** [comment]
Signed-off-by: sigmasd

**Comment by florianduros** [comment]
Hello !
First of all, thank you for contribution!

Currently we are not supporting officially deno so I'm concerned to add documentation about it.

**Comment by sigmaSd** [comment]
Hi that's reasonable, maybe instead of this we can add one line that says `you can use this sdk with deno (using npm compat) but it's not officially supported`
its working great so far in my couple of days testing

**Review by florianduros — APPROVED** [review]
LGTM thanks!

**Pull request merged**
