### PR TITLE
Remove default timeout on Sync

### PR DESCRIPTION
**Pull request by pik**
There is currently no backup strategy for low-bandwidth connections which cannot complete a  `/sync` within `localTimeoutMs` -- this means that slow connections will *never* load riot-web as the set of state events even for several popular rooms is [very large](https://github.com/vector-im/riot-web/issues/2825#issuecomment-270692398) - this removes the localTimeoutMs entirely from the default `/sync` calls (it can still be set via `client.opts`) as per https://github.com/vector-im/riot-web/issues/2737#issuecomment-271740918.

### CODE REVIEW

**Comment by ara4n** [comment]
I wonder whether removing the client timeout means that if you lose your connectivity during a sync (e.g. by sleeping your laptop, or switching network, etc), the sync will never timeout and the client will never recover from the outage, wedging solid.

Unless the keepAlives logic is adequate to recover from that scenario...

@kegsay, wdyt?

**Comment by pik** [comment]
The browser should fail with either, `net::ERR_INCOMPLETE_CHUNKED_ENCODING` `net::ERR_NETWORK_CHANGED` etc. I think? Is there a case where the browser might not set request status to `failed` ?

**Comment by Kegsay** [comment]
In practice, browsers **do not** fail and just wedge entirely. Notably, Safari does this. This is why `localTimeoutMs` is A Thing. I can't accept this PR because it will break other users.

**Comment by pik** [comment]
> In practice, browsers do not fail and just wedge entirely. Notably, Safari does this

Really? In my testing both Firefox and Chromium fail correctly, is there an open bug for this in Safari? 

At any-rate if this is a possibility we have to contend with - what about hooking into `onprogress` to debounce the timeout event?

**Comment by Kegsay** [comment]
> what about hooking into onprogress to debounce the timeout event?

That's what I would prefer.

**Comment by richvdh** [comment]
I think this got superceded by #330, and thence #392.

**Pull request closed without merging**
