### PR TITLE
Hide pending events in thread timelines

### PR DESCRIPTION
**Pull request by gsouquet**
Fixes https://github.com/vector-im/element-web/issues/23684

## Checklist

* [x] Tests written for new code (and old code if feasible)
* [x] Linter and other CI checks pass
* [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

---
Here's what your changelog entry will look like:

## 🐛 Bug Fixes
 * Hide pending events in thread timelines ([\#2843](https://github.com/matrix-org/matrix-js-sdk/pull/2843)). Fixes vector-im/element-web#23684.

### CODE REVIEW

**Comment by t3chguy** [comment]
@gsouquet did you identify what regressed this behaviour?

**Comment by gsouquet** [comment]
@t3chguy yes, https://github.com/vector-im/element-web/issues/23684 

it's quite an unexpected behaviour IMO. the default should be the opposite in my opinion

**Comment by t3chguy** [comment]
@gsouquet that's the issue this fixes, I don't see the pr/commit which introduced the regression, got a link to that by any chance?

**Comment by gsouquet** [comment]
Sorry wrong copy/paste

**Review by richvdh — APPROVED** [review]

**Comment by richvdh** [comment]
seems reasonable to me, but I should probably ask if there could be tests for this?

**Pull request merged**
