### PR TITLE
Add support for `fetch` and cbor

### PR DESCRIPTION
**Pull request by Half-Shot**
This does quite a few sweeping changes to support `fetch`, `CBOR encoding` and the `Accept` header which is part of https://github.com/matrix-org/matrix-doc/pull/1740.  **Please do not merge or review this just yet** 

Anyway, this PR seems to work perfectly fine with a few issues noted below.

Notable failings:
- `supportsCbor` is always true, and not detected. Ergo, this PR breaks support for regular JSON servers.
- I had to swap `request` for fetch because I could not get ArrayBuffer responses out of it which is important.
- `borc` is the library we are using for `cbor` and is wasmy, untested, and seems to work most of the time.

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by bradjones1** [comment]
The related MSC hasn't gone anywhere for a few years but `fetch` support would be good to have. Might be advisable to break out the CBOR-related components to make this more atomic.

**Comment by gsouquet** [comment]
It appears that native `fetch` support has been merged in Node.js quite recently, https://github.com/nodejs/node/pull/41749

**Comment by 3nprob** [comment]
> It appears that native `fetch` support has been merged in Node.js quite recently, [nodejs/node#41749](https://github.com/nodejs/node/pull/41749)

Noteworthy that the v18+ implementation is provided by [`undici`](https://github.com/nodejs/undici), so using that as a polyfill should ensure minimal differences between the versions.

**Comment by t3chguy** [comment]
Closing this as it no longer applies cleanly

**Comment by 3nprob** [comment]
Is the current intention still to go with fetch APIs across the board (last update I can see on the matter) or is still still up for reconsideration?

**Comment by t3chguy** [comment]
Yes, fetch given native browser and node support

**Pull request closed without merging**
