### PR TITLE
De-duplicate code and fix types

### PR DESCRIPTION
**Pull request by t3chguy**
---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by kerryarchibald — APPROVED** [review]
LGTM

**Comment by YousefED** [comment]
I don't think the change in types for `members()` parameters in this PR is correct.

```
includeMembership?: string,
excludeMembership?: string,
```
should both still accept a `string[]`, because we can filter multiple membership types. If the expected input is a comma-separated list, this should be documented? (but afaik passing in an array works)

**Comment by t3chguy** [comment]
@YousefED https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3roomsroomidmembers says the field takes a single enum value, not an array of values

**Comment by YousefED** [comment]
> @YousefED https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3roomsroomidmembers says the field takes a single enum value, not an array of values - if Synapse supports an array then the spec needs to consider updating to document that

Damn, you're right! My bad. I was probably confused by the previous (wrong) signature though. I think the spec is a bit weird (why would you need an OR between the two parameters), but it seems like Synapse is also built to handle it this way.

I'll fix my application instead. Appreciate your reply

**Pull request merged**
