### PR TITLE
Switch to /kick API

### PR DESCRIPTION
**Pull request by aaronraimist**
Fixes https://github.com/vector-im/element-web/issues/19018

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
This sort of issue is a bit of a catch-22: landing this ahead of the Synapse change means Element is at risk of reopening the bug regarding unintentional unbans, but the same happens if Synapse lands their changes first.

I think it's best if we figure out coordination at a higher level than code review in the independent projects (cc @anoadragon453 ) - will raise internally.

**Comment by aaronraimist** [comment]
Actually I think it should be fine to land this first. `/kick`ing someone who is banned doesn't seem to do anything right now.

**Comment by novocaine** [comment]
Finding this hard to evaluate this because the description of the user impact isn't all in one place - there's a rolling discussion across many tickets, and the tickets are spec-centric, not user centric. Can we summarise the user impact of this change here please? 

There are other home servers and other clients to consider, as well:

* What's the user impact of releasing the Synapse change on other clients in the ecosystem, prior to them updating to the latest `matrix-js-sdk`?
* What's the user impact of updating Element if the home server administrator does not update Synapse in a timely fashion, or if another home server is used such as conduit or dendrite?

**Comment by aaronraimist** [comment]
There should be no impact on users. This is an internal change that just switches from manually sending `m.room.member` events to using the proper Matrix API for kicking. The spec says

> It is preferable to use the membership APIs (/rooms/<room id>/invite etc) when performing membership actions rather than adjusting the state directly

https://spec.matrix.org/unstable/client-server-api/#room-membership

There is no need to update Synapse for this change to work. This API has been around in the spec like 2016 https://matrix.org/docs/spec/client_server/r0.1.0#post-matrix-client-r0-rooms-roomid-kick. Any server not implementing it would be at fault, not Element. I have not tested against Dendrite or Conduit but Element already uses the proper APIs for /ban /unban /leave and /invite so I'm sure those servers implement /kick as well.

**Comment by Palid** [comment]
@novocaine @aaronraimist would it make sense to have a fallback for the old way in case the new and proper way fails? I don't think it'll hurt, but this way we'll have proper compatibility even if something implements it incorrectly.

**Comment by novocaine** [comment]
> I have not tested against Dendrite or Conduit but Element already uses the proper APIs for /ban /unban /leave and /invite so I'm sure those servers implement /kick as well.

I think we should test this or at least check if their code looks like they implement /kick - it would be quite unfortunate if EW inadvertently lost the ability to kick people on certain home servers.

**Comment by turt2live** [comment]
Conduit and Dendrite both have route handlers for `/kick`. 

Merging this as Synapse appears to have landed their side. We should watch out for issues.

**Pull request merged**
