### PR TITLE
Update the olm library version to 1.3.0

### PR DESCRIPTION
**Pull request by NegativeMjark**

### CODE REVIEW

**Comment by ara4n** [comment]
What will be the symptoms of the migration to 1.3.0?

**Comment by NegativeMjark** [comment]
> What will be the symptoms of the migration to 1.3.0?

Any exist OlmGroupSessions won't unpickle. But those aren't persisted across restarts anyway. So that change won't have any affect.
Attempts to share keys with older versions will fail.
Existing sessions should continue to work.

**Comment by ara4n** [comment]
lgtm modulo lint.

**Comment by ara4n** [comment]
holding off on merge until cutting the next staging release (qv)

**Pull request merged**
