### PR TITLE
Fix filepanel also filtering main timeline with LL turned on.

### PR DESCRIPTION
**Pull request by bwindels**
Fixes https://github.com/vector-im/riot-web/issues/7262

### CODE REVIEW

**Comment by ara4n** [comment]
looks plausible. would be good to get a comment about why this is needed though (as i'm failing to see why/where the timeline filter ever gets written into this object?)

**Comment by bwindels** [comment]
@ara4n Here: https://github.com/matrix-org/matrix-js-sdk/pull/716/commits/3363cc4f1d97a7556373db7bab321f4581d81e66#diff-cf27c1d543e886c89cd9ac8b8aeaf05bR2154

If the method got called once with both the LL & timeline filter (anytime you open the filepanel with LL enabled), the timeline filter would modify the original LL filter object, persisting the filepanel filter on the LL filter.

**Comment by ara4n** [comment]
right. lgtm then - just need to get the comment in the code to spell out where the 'bad' assign happens to avoid someone breaking it or getting confused by it in future.

**Comment by bwindels** [comment]
Right, will do!

**Comment by bwindels** [comment]
@ara4n ready for another look

**Comment by ara4n** [comment]
lgtm!

**Pull request merged**
