### PR TITLE
Add `logout`

### PR DESCRIPTION
**Pull request by dbkr**

### CODE REVIEW

**Comment by richvdh** [comment]
1. any reason not to put this in MatrixBaseApis ?
2. the lint is sad about something

**Comment by dbkr** [comment]
I was imagining this ought to go in MatrixBaseApis but the rest of the login stuff is in client so I kept it with that.

**Comment by richvdh** [comment]
> I was imagining this ought to go in MatrixBaseApis but the rest of the login stuff is in client 

That's because `login` refers to `this.deviceId`, which, as we've discussed elsewhere, may be a mistake. I'd rather see `logout` go straight into `MatrixBaseApis`.

**Comment by dbkr** [comment]
Ah, I see. Done.

**Pull request merged**
