### PR TITLE
Fix state_events.ts types

### PR DESCRIPTION
**Pull request by t3chguy**
Regressed by https://github.com/matrix-org/matrix-js-sdk/pull/4105

### CODE REVIEW

**Comment by richvdh** [comment]
If this is a "fix", please could you link to the PR that broke it and describe what was broken, for future archaeologists?

**Comment by richvdh** [comment]
The change looks right, but I'm somewhat surprised we didn't discover the problem sooner. Don't we hit this codepath in Element Web?

**Comment by t3chguy** [comment]
> Don't we hit this codepath in Element Web?

Looks like it is due to explicit typecasts on the React SDK callers

image
image

**Comment by richvdh** [comment]
> Looks like it is due to explicit typecasts on the React SDK callers

(we should probably remove those typecasts)

**Review by richvdh — APPROVED** [review]

**Comment by t3chguy** [comment]
> (we should probably remove those typecasts)

Yup, have a changeset brewing locally with that and switching from the deprecated type

**Comment by t3chguy** [comment]
It's now in https://github.com/matrix-org/matrix-react-sdk/pull/12513

**Pull request merged**
