### PR TITLE
Fix IndexedDB store creation example

### PR DESCRIPTION
**Pull request by florianjacob**
This seems like a simple oversight. However, I have no idea whether this is really correct, please verify this.

Signed-off-by: Florian Jacob <florian ÄT wolkenplanet <POINT> de>

### CODE REVIEW

**Comment by florianjacob** [comment]
Seems like the example is even more broken, and missing an `opts = { indexeddb: window.indexeddb }` or something similar.

**Comment by jryans** [comment]
> Seems like the example is even more broken, and missing an `opts = { indexeddb: window.indexeddb }` or something similar.

Yes, looks like that's correct, at the moment `indexedDB: window.indexedDB` is expected to be passed as well (or an equivalent when running on NodeJS). @florianjacob, would you like to add this tweak to your PR?

**Comment by florianjacob** [comment]
Tweak added. :+1:

**Review by jryans — APPROVED** [review]
Thanks for working on this, and sorry for the long delay... 😓

**Pull request merged**
