### PR TITLE
Revert "Fix room state being updated with old (now overwritten) state and emitting for those updates. (#4242)"

### PR DESCRIPTION
**Pull request by toger5**
This reverts commit 957329b21821c0f632de6c04fff53144f7c0e5dd.
@hughns @t3chguy 
With the resent state_after changes this seems to not be required anymore right?

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md)).

### CODE REVIEW

**Comment by t3chguy** [comment]
> With the resent state_after changes this seems to not be required anymore right?

Those changes haven't landed yet and this is a breaking change as a parameter is being removed, it'd need to either be bundled into the same breaking release as the state_after stuff or need a deprecation period

**Comment by t3chguy** [comment]
Where even was isStartTimelineState ever true?

**Comment by toger5** [comment]
> Where even was isStartTimelineState ever true?

This was discussed sync. But for the protocol i will link it here:
https://github.com/matrix-org/matrix-js-sdk/blob/325dace4377ccd8d53e26f3e0b706876fdaf4e20/src/models/event-timeline.ts#L130

@t3chguy, Is this ready to get merged?

**Comment by t3chguy** [comment]
I think this should land in the same release as the MSC4222 PR, and that's being held until after the next RC due to the risk level

**Review by t3chguy — APPROVED** [review]

**Pull request merged**
