### PR TITLE
ci: support matching branch names in complement-crypto

### PR DESCRIPTION
**Pull request by kegsay**
So you can make a branch `foo` and having CI run tests against the same named branch `foo` on the complement-crypto repo. This allows tests to be added during the PR process.

### CODE REVIEW

**Comment by t3chguy** [comment]
Wouldn't this break if you land the js SDK pr via merge queue but don't have perms to land the complement pr, breaking All later merge queue runs.

**Comment by kegsay** [comment]
> but don't have perms to land the complement pr, breaking All later merge queue runs.

For us I guess we will have perms, but for outsiders this is true. I can close this PR if you'd prefer to keep tracking `main`?

**Comment by t3chguy** [comment]
I don't have merge perms on that complement crypto, nor do I think I should

**Comment by kegsay** [comment]
What's the desired outcome here? If we don't want matching branch logic (because tests only run in the merge queue) then this should be closed.

**Comment by t3chguy** [comment]
Either the branch matching needs to solve the problem outlined above or it'd cause more problems imo

**Comment by kegsay** [comment]
Going to close this on the basis that:
 - complement crypto does not run on PR commits, only merge queue to develop
 - hence so long as the test has landed on complement crypto first, the merge queue will pass.

**Pull request closed without merging**
