### PR TITLE
Support for blacklisting unverified devices, both per-room and globally

### PR DESCRIPTION
**Pull request by ara4n**
Builds on #335, which should be landed before this review makes any sense.

Twinned with https://github.com/matrix-org/matrix-react-sdk/pull/636.

Hopefully solves https://github.com/vector-im/riot-web/issues/2313

### CODE REVIEW

**Comment by richvdh** [comment]
The main thing outstanding here seems to be persistence of the settings.

**Comment by richvdh** [comment]
> The main thing outstanding here seems to be persistence of the settings.

I see that https://github.com/matrix-org/matrix-react-sdk/pull/636 contains functionality to persist the user setting, but we still need to save the room setting somehow.

**Comment by ara4n** [comment]
persisting roomsettings is done in https://github.com/matrix-org/matrix-react-sdk/pull/636/files#diff-7810353d2ee5218b7242e81423030433R279 no?

**Comment by richvdh** [comment]
> persisting roomsettings is done in https://github.com/matrix-org/matrix-react-sdk/pull/636/files#diff-7810353d2ee5218b7242e81423030433R279 no?

ahhh, that's meant to be a per-user setting - got it

**Comment by ara4n** [comment]
@richvdh now the other PR has landed, this is unblocked. is this LGTMed?

**Pull request merged**
