### PR TITLE
Better fallback for unavailable event age

### PR DESCRIPTION
**Pull request by toger5**
This fixes an issue where state (particularly call member state) events were not considered expired even if they were very old. Resulted in us showing really old calls for rooms.
This applies: https://github.com/matrix-org/matrix-js-sdk/pull/3839 again after the tests were fixed downstream in the react sdk. https://github.com/matrix-org/matrix-react-sdk/pull/11827

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

---
This change is marked as an *internal change* (Task), so will not be included in the changelog.

### CODE REVIEW

**Comment by toger5** [comment]
Is there a way to run downstream test in the PR? without adding it to the merge queue?

**Comment by t3chguy** [comment]
@toger5 no, only locally

**Comment by toger5** [comment]
I ran the unit tests for the matrix-react-sdk about 10 times now and they all succeeded with the fix from Midhun https://github.com/matrix-org/matrix-react-sdk/pull/11827 with this js-sdk pr.

**Review by dbkr — APPROVED** [review]
If you could put in the title / description that this is the same PR re-applied that would be good - took me diffing the PR against the old one to realise it was the same PR. :)

**Pull request merged**
