### PR TITLE
Lazy loading: avoid loading members at initial sync for e2e rooms

### PR DESCRIPTION
**Pull request by bwindels**

### CODE REVIEW

**Comment by bwindels** [comment]
This should be ready to have a look now

**Comment by bwindels** [comment]
Ideally I wanted to add some devicelist integration tests to this as well, with LL enabled, but couldn't figure out how the http mocking is supposed to work, so I'll do it in another PR.

**Comment by bwindels** [comment]
Addresses https://github.com/vector-im/riot-web/issues/7182 (Item 2 in the list)

**Comment by ara4n** [comment]
why would you need http mocking for e2e tests btw?

**Comment by bwindels** [comment]
@ara4n Not sure if you're think of the e2e tests. I mean the integration tests for e2e encryption device lists (e.g. `spec/integ/devicelist-integ-spec`). We use `MockHttpBackend` there...

**Comment by bwindels** [comment]
Started writing a test on `bwindels/lldevicelisttest` btw, I get `Error: Timed out after flushing 1 requests; 3 remaining`. Plan to continue on it later on.

**Comment by bwindels** [comment]
The RR issue really looks the same as item 6, it's just the catchup sync taking a long time.

**Pull request merged**
