### PR TITLE
[WIP] Upgrade to babel@7 and support TypeScript

### PR DESCRIPTION
**Pull request by turt2live**
**See https://github.com/matrix-org/matrix-react-sdk/pull/3292**

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/983

### CODE REVIEW

**Comment by Half-Shot** [comment]
This is awesome. Good luck.

As an aside, when this is complete we can start to support TS in `matrix-appservice-bridge` too.

**Comment by t3chguy** [comment]
Upgrade to babel@7 means we can also use Jest@24 instead of being pinned @23 :D

**Comment by turt2live** [comment]
We can fix https://github.com/vector-im/riot-web/issues/11524 with this too, probably.

**Comment by turt2live** [comment]
Fixed/replicated by https://github.com/matrix-org/matrix-js-sdk/pull/1112

**Pull request closed without merging**
