### PR TITLE
Use existing session id for fetching flows as to not get a new session

### PR DESCRIPTION
**Pull request by t3chguy**
Fixes https://github.com/vector-im/riot-web/issues/13990

Regression caused by https://github.com/matrix-org/matrix-js-sdk/commit/bebeec7d84295a994036502974e76f3327ef842f

### CODE REVIEW

**Comment by clokep** [comment]
> hmm, I'm fairly sure we're supposed to know the flows by here. Would be good to test with a homeserver like conduit as Synapse doesn't validate the session correctly.

Would love to have more info on what the issues are with how Synapse validates the session! We've put a bunch of work into this recently, so if there are other issues it'd be nice to fix it while the info is still in someone's head!

**Comment by t3chguy** [comment]
> hmm, I'm fairly sure we're supposed to know the flows by here

Not if we come in from an email verification apparently as we get the session id from the URL and <InteractiveAuth calls this method after passing that ID to the ctor but it gets thrown away by us using null

**Comment by turt2live** [comment]
> Would love to have more info on what the issues are with how Synapse validates the session! We've put a bunch of work into this recently, so if there are other issues it'd be nice to fix it while the info is still in someone's head!

@clokep I believe it came down to spec compliance last I looked: Synapse happily accepted `{}` as an auth dict even when it's not supposed to, and likewise somehow manages to track different session IDs across the same request for the same user (as under some conditions riot-web loses its session ID and just gets a new one in the middle of the flow).

**Comment by clokep** [comment]
> likewise somehow manages to track different session IDs across the same request for the same user

It definitely doesn't do this. There are some hacks added though for updating sessions and such through the UI Auth flow, which are all...not really speced. :(

**Comment by t3chguy** [comment]
Registering on a Conduit worked but then again it didn't have many flows (no email or consent) so maybe coincidental.

**Pull request merged**
